### ISSUE TITLE
(401) Unauthorized

### ISSUE THREAD

**Issue by Lukasz-Kukawski** [tsrob50/SendGridFunction#1]
I am getting error 
> Error with Invoke-RestMethod The remote server returned an error: (401) Unauthorized.

any clue what can be wrong?
Getting the same error if I run it from ISE or in Azure Runbook.

**Comment by tsrob50** [comment]
the 401 indicates an issue with the SendGrid endpoint.  Be sure that the API key is corrected and you are using the API Key, not the API Key ID in the script.

Thanks,
Travis

**Comment by Lukasz-Kukawski** [comment]
It is working now. I created new API key and pasted whole code to new document. 
thanks
